### ISSUE TITLE
*** [EN] Roadmap ***

### ISSUE THREAD

**Issue by devinterx** [devinterx/telegraph#1]
At next half year
- [ ] Authorization to Web Interface (Web) by Telegram API
- [ ] First init bot
   - [ ] Setting
   - [ ] Create Administrator
- [ ] Web: Users permission manager
- [ ] Web: Scenes manager
- [ ] Web: Users manager, States (Saves) editors
- [ ] Bot: Scene handler
- [ ] Web: Items manager
- [ ] Web: Locationsmanager
- [ ] Bot: Items handler
- [ ] Bot: Location handler
- [ ] Bot & Web locations mutators
- [ ] Trading
- [ ] Quests
- [ ] NPC System
- [ ] Enemy, battle system
