### ISSUE TITLE
*** [RU] Roadmap ***

### ISSUE THREAD

**Issue by devinterx** [devinterx/telegraph#2]
В ближайшие полгода
- [x] Авторизация в веб интерфейс через бота в телеграмме
- [ ] Первый запуск бота и его инициализация
   - [ ] Настройки
   - [ ] Создание администратора
- [ ] Web: Менеджер прав пользователя
- [ ] Web: Менеджер сцен
- [ ] Web: Менеджер пользователей, Редактор сохранений
- [x] Bot: Обработчик сцены
- [ ] Web: Менеджер предметов
- [ ] Web: Менеджер локаций
- [ ] Bot: Обработчик предметов
- [ ] Bot: Обработчик локаций
- [ ] Bot & Web: Мутация локаций
- [ ] Торговля
- [ ] Квесты
- [ ] Система неписей
- [ ] Враги, обработка боя
